### ISSUE TITLE
No cards info in exported csv

### ISSUE THREAD

**Issue by panlibra** [bitwarden/help#460] opened 2021-03-08 02:53 UTC
no cards information found in csv file when exported the whole vault while did find in json file.  Hope it be fixed.

**Comment by Greenderella** [comment] 2021-03-08 11:54
Hi @panlibra,

This is the intended behaviour. Bitwarden recommends using .json for a more complete option for standard backup procedures as .csv exports will not export Cards or Identities.

More information here: https://bitwarden.com/help/article/export-your-data/

**Comment by fschillingeriv** [comment] 2021-03-11 17:36
Thanks @Greenderella! Closing this issue 😄

**Closed by fschillingeriv** 2021-03-11 17:36 UTC
